#!/bin/bash -xv

set -nounset
set -e

if [ "$1" != "account" -a "$1" != "hub" -a "$1" != "hook" ]; then
    echo "Usage: buildjob [account|hub|hook] [version]"
    exit 1
fi

make build_cross_"$1"
cd make
docker build -t "$1" -f "$1"/"$1".dockerfile .
docker tag "$1" index-dev.qiniu.io/kelibrary/"$1":"$2"
docker push index-dev.qiniu.io/kelibrary/"$1":"$2"
cd ../
