apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: 'backend'
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-10T14:40:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020\\-02-10T14:41:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-10T14:41:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-10T14:40:17Z"
    status: "True"
    type: PodScheduled
